<?php if ($this->pageCount): ?>
    <div class="row">
        <div class="col-sm-12">

            <ul class="pagination pagination-sm">
                <!-- Previous page link -->
                <?php if (isset($this->previous)): ?>
                    <li>
                        <a href="<?php echo $this->url() . $this->action . "/" . $this->previous; ?>">
                            <span class="glyphicon glyphicon-arrow-left"></span>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="disabled">
                        <a href="#">
                            <span class="glyphicon glyphicon-arrow-left"></span>
                        </a>
                    </li>
                <?php endif; ?>
                <!-- Numbered page links -->
                <?php foreach ($this->pagesInRange as $page): ?>
                    <?php if ($page != $this->current): ?>
                        <li>
                            <a href="<?php echo $this->url() . $this->action . "/" . $page; ?>">
                                <?php echo $page; ?>
                            </a>
                        </li>
                    <?php else: ?>
                        <li class="active">
                            <a href="#"><?php echo $page; ?></a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>

                <!-- Next page link -->
                <?php if (isset($this->next)): ?>
                    <li>
                        <a href="<?php echo $this->url() . $this->action . "/" . $this->next; ?>">
                            <span class="glyphicon glyphicon-arrow-right"></span>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="disabled">
                        <a href="#">
                            <span class="glyphicon glyphicon-arrow-right"></span>
                        </a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>