<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?php echo $this->translate('Login') ?>
            </div>
            <div class="panel-body">
                <?php
                $form = $this->form;
                $form->prepare();
                ?>
                <div class="row">
                    <div class="col-lg-12">
                        <?php echo $this->form()->openTag($form); ?>
                        <fieldset>
                            <div class="form-group">
                                <label
                                    class="control-label col-sm-4 lbl-sm"><?php echo $this->translate('Username') ?></label>

                                <div class="col-sm-8">
                                    <?php echo $this->formRow($form->get('username')); ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label
                                    class="control-label col-sm-4 lbl-sm"><?php echo $this->translate('Password') ?></label>

                                <div class="col-sm-8">
                                    <?php echo $this->formRow($form->get('password')); ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-8 pull-right">
                                    <?php $form->get('submit')->setValue($this->translate('Login')) ?>
                                    <?php echo $this->formSubmit($form->get('submit')); ?>
                                    <label class="lbl-sm">
                                        <?php echo $this->formRow($form->get('remember')); ?>
                                        <?php echo $this->translate('Keep me signed in') ?>
                                    </label>
                                </div>
                            </div>
                            <?php if ($this->message) : ?>
                                <div class="form-group">
                                    <div class="col-sm-8 pull-right">
                                        <div class="alert alert-dismissable alert-danger">
                                            <button type="button" class="close" data-dismiss="alert">×</button>
                                            <span class="glyphicon glyphicon-thumbs-down"></span>
                                            <?php echo $this->translate($this->message) ?>
                                            <?php $this->translate('Invalid username or password') ?>
                                        </div>
                                    </div>
                                </div>
                            <?php endif ?>
                        </fieldset>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

