<div class="container">
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <?php echo $this->translate('Registration')?>
                </div>
                <div class="panel-body">
                    <?php
                    $form = $this->form;
                    $form->prepare();
                    ?>
                    <div class="row">
                        <div class="col-lg-12">
                            <?php echo $this->form()->openTag($form); ?>
                            <fieldset>
                                <div class="form-group">
                                    <label class="control-label col-sm-4"><?php echo $this->translate('Username')?></label>

                                    <div class="col-sm-8">
                                        <?php echo $this->formRow($form->get('username')); ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-4"><?php echo $this->translate('Password')?></label>

                                    <div class="col-sm-8">
                                        <?php echo $this->formRow($form->get('password')); ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-4"><?php echo $this->translate('Confirm Password')?></label>

                                    <div class="col-sm-8">
                                        <?php echo $this->formRow($form->get('confirmPassword')); ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-8 pull-right">
                                        <?php echo $this->formSubmit($form->get('submit')); ?>
                                    </div>
                                </div>
                                <?php if ($this->message) : ?>
                                    <div class="form-group">
                                        <div class="col-sm-8 pull-right">
                                            <div class="alert alert-dismissable alert-danger">
                                                <button type="button" class="close" data-dismiss="alert">×</button>
                                                <?php if ($this->message) echo $this->translate($this->message); ?>
                                            </div>
                                        </div>
                                    </div>
                                <?php endif ?>
                            </fieldset>
                            <?php echo $this->form()->closeTag(); ?>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    Provide username and password to login to system
                </div>
            </div>
        </div>

    </div>
</div>
