<?php
$user = $this->identity();
?>
<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
        <?php if ($this->hideForm == false) : ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <?php echo $this->translate('Settings') ?>
                </div>
                <div class="panel-body">
                    <?php
                    $form = $this->form;
                    $form->get('username')->setValue($user->getUsername());
                    $form->get('email')->setValue($user->getEmail());
                    $form->get('name')->setValue($user->getName());
                    $form->get('phone')->setValue($user->getPhone());
                    $form->get('description')->setValue($user->getDescription());
                    $form->prepare();
                    ?>
                    <?php if ($this->message) : ?>
                        <div class="row">
                            <div class="col-lg-12">

                                <div class="alert alert-dismissable alert-success">
                                    <span class="glyphicon glyphicon-thumbs-up"></span>
                                    <?php echo $this->translate($this->message) ?>
                                </div>
                            </div>
                        </div>
                    <?php endif ?>
                    <div class="row">
                        <div class="col-lg-12">
                            <?php echo $this->form()->openTag($form); ?>
                            <fieldset>
                                <div class="form-group">
                                    <label
                                        class="control-label col-sm-4 lbl-sm"><?php echo $this->translate('Username') ?></label>

                                    <div class="col-sm-8">
                                        <?php echo $this->formRow($form->get('username')); ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label
                                        class="control-label col-sm-4 lbl-sm"><?php echo $this->translate('Full Name') ?></label>

                                    <div class="col-sm-8">
                                        <?php echo $this->formRow($form->get('name')); ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label
                                        class="control-label col-sm-4 lbl-sm"><?php echo $this->translate('Email') ?></label>

                                    <div class="col-sm-8">
                                        <?php echo $this->formRow($form->get('email')); ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label
                                        class="control-label col-sm-4 lbl-sm"><?php echo $this->translate('Phone Number') ?></label>

                                    <div class="col-sm-8">
                                        <?php echo $this->formRow($form->get('phone')); ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label
                                        class="control-label col-sm-4 lbl-sm"><?php echo $this->translate('Description') ?></label>

                                    <div class="col-sm-8">
                                        <?php echo $this->formRow($form->get('description')); ?>
                                    </div>
                                </div>
                                <hr>
                                <div class="form-group">
                                    <label
                                        class="control-label col-sm-4 lbl-sm"><?php echo $this->translate('Password') ?></label>

                                    <div class="col-sm-8">
                                        <?php echo $this->formRow($form->get('password')); ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-8 pull-right">
                                        <?php $form->get('submit')->setValue($this->translate('Save')) ?>
                                        <?php echo $this->formSubmit($form->get('submit')); ?>
                                    </div>
                                </div>
                            </fieldset>
                            <?php echo $this->form()->closeTag(); ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>

