<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><span
                    class="glyphicon glyphicon-paperclip"></span>&nbsp;<?php echo $this->translate('Skeleton Application') ?>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <?php
            echo $this->navigation('navigation')
                ->menu()
                ->setMinDepth(0)
                ->setMaxDepth(0)
                ->setUlClass('nav navbar-nav');
            ?>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate('Account') ?>
                        <b class="caret"></b></a>
                    <?php if ($this->identity()) : ?>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li><a href="/logout"><?php echo $this->translate('Logout') ?></a></li>
                        </ul>
                    <?php endif ?>
                    <?php if (!$this->identity()) : ?>
                        <ul class="dropdown-menu">
                            <li><a href="/login"><?php echo $this->translate('Login') ?></a></li>
                            <li><a href="/register"><?php echo $this->translate('Register') ?></a></li>
                        </ul>
                    <?php endif ?>
                </li>
            </ul>
        </div>
    </div>
</nav>


<div class="container">
    <?php
    echo $this->navigation('navigation')
        ->menu()
        ->setMinDepth(1)
        ->setMaxDepth(1)
        ->setUlClass('nav nav-pills');
    ?>
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <div class="row">
            <div class="col-sm-10">
                &copy; 2005 - <?php echo date('Y') ?> by Viscomp Ltd. Masarliev team
            </div>
            <div class="col-sm-2">
            </div>
        </div>
    </footer>
</div>
<!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
